### ISSUE TITLE
Add support for automatic cluster node discovery

### ISSUE THREAD

**Issue by brandtol** [IBMStreams/streamsx.elasticsearch#23]
Elasticsearch provides a 'nodeDiscovery' feature for clusters. Any node can be queried to get a list of currently available nodes and their roles. Client applications can use this feature to check for changes in the cluster and adapt their internal settings. This feature will help the client to handle planned cluster changes and unplanned outages.

**Tasks**
- [ ] add parameters `discoveryEnabled`  and  `discoveryFrequency` to specify if and how often discovery will be done
- [ ] add parameter `dicoveryFilter` to allow filtering the node roles (eg. only data nodes will be returned)
- [ ] configure JEST client to enable discovery
- [ ] test with several outage scenarios
- [ ] test with SSL enabled
- [ ] documentation, sample
